version: '3.8'
services:
  frontend:
    build:
      context: ./path/to/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./path/to/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DB: exampledb

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
