version: '3.8'
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - server

  server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.sql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-db/create_schema.sql:/data/application/init.sql

volumes:
  db-data:
