version: '3.8'
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - server

  server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_DOCKER_PORT: ${MYSQL_DOCKER_PORT}
      NODE_DOCKER_PORT: ${NODE_DOCKER_PORT}
    

  db:
    image: mysql:8.3
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    command: --init-file /data/application/init.sql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
    volumes:
      - ./mysql-db/create_schema.sql:/data/application/init.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:
